# Travis config file
# ==================

language:
  python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

branches:
  only:
    - master

# Install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt --quiet
  - pip install pytest
  - pip install coveralls

# Run automated tests
script:
  - sh runtests.sh

after_success:
- coveralls
